monitoring:
  interval: 60  # monitoring interval in seconds
  
server_monitoring:
  enabled: true
  cpu_threshold: 80  # CPU usage threshold percentage
  memory_threshold: 80  # Memory usage threshold percentage
  disk_threshold: 90  # Disk usage threshold percentage

container_monitoring:
  enabled: true
  containers:
    - name: "web-service"
      port: 8080
    - name: "database"
      port: 5432

alert:
  email:
    enabled: true
    smtp_host: "smtp.gmail.com"
    smtp_port: 587
    username: "your-email@gmail.com"
    password: "your-app-password"
    from: "your-email@gmail.com"
    to: 
      - "admin@example.com"
    subject_prefix: "[Monitoring Alert]"
